modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="cnc" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Caves & Cliffs" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png" #optional
credits="Thanks to Mojang" #optional
authors="LoreSchaeffer" #optional
description='''
This mod aim to recreate some of the Caves & Cliffs update in Minecraft 1.16.
'''

[[dependencies.cnc]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cnc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
